# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('TransifexNativeSDK/**/*.gradle*', 'TransifexNativeSDK/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      working-directory: ./TransifexNativeSDK
      run: chmod +x gradlew
    - name: Unit Test
      working-directory: ./TransifexNativeSDK
      run: ./gradlew test
    - name: Cleanup Gradle Cache
      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: unitTestReports
        path: |
          TransifexNativeSDK/clitool/build/reports/tests/test/
          TransifexNativeSDK/common/build/reports/tests/test/
          TransifexNativeSDK/txsdk/build/reports/tests/
